//
// Created by arthur on 10/11/2024.
//

#ifndef CONCERTO_REFLECTION_DEFINE_HPP
#define CONCERTO_REFLECTION_DEFINE_HPP

#include <Concerto/Core/Types.hpp>

#ifdef CCT_REFLECTION_BUILD
#define CCT_REFLECTION_API CCT_EXPORT
#else
#define CCT_REFLECTION_API CCT_IMPORT
#endif // CCT_REFLECTION_BUILD

#endif //CONCERTO_REFLECTION_DEFINE_HPP